[package]
name = "image-to-image-masking"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
stabilityai = { path = "../../stabilityai" }
tokio = { version = "1.32.0", features = ["full"] }
